name: Terraform Destroy Manual

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type YES to confirm destruction of infrastructure"
        required: true

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm_destroy == 'YES' }}
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›’ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ” Write GCP credentials
        run: |
          echo "${{ secrets.SA }}" > key.json

      - name: ðŸ§± Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: ðŸš€ Terraform Init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/key.json
        run: terraform init -input=false

      - name: ðŸ’¥ Terraform Destroy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/key.json
        run: terraform destroy -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm_destroy == 'YES'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/key.json
        run: terraform destroy -auto-approve        
        